### ISSUE TITLE
setup.py Python version?

### ISSUE THREAD

**Issue by zigastegu** [tai/python-ucdev#1]
Thank you for sharing this interface.
I suppose this was written with Python2 syntax in mind?

print "w:", " ".join(["{:08b}".format(i) for i in wbuf])
[setup.py_install_output.txt](https://github.com/tai/python-ucdev/files/1539553/setup.py_install_output.txt)

**Comment by tai** [comment]
Thanks for reporting.
Python3 was barely on my mind at the time when I first wrote this.
I have made a major rewrite and it should now supports both Python 2 and 3.
